# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e2cdf01eed1ea93feab9838f568c2d64036f06ce935919de4cb09285d3792d09387b84f00e842c2204448f9e5143e8ee38f05fa8465fd9e51cd3cadfac9b042

test:
  secret_key_base: f86ab8ef6f5c2987194e22cc5884b52e66f533f775871b8b3e609c2f3d89fdc9526d3a25312a7be2d1f4dfa2eb0aee8b184c2bead74435fc98dbb77a3373881c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
